services:
  db:
    image: mariadb:11.5
    container_name: mariadb_container
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: 1234
      MARIADB_DATABASE: ttalkkag
      MARIADB_USER: root
      MARIADB_PASSWORD: 1234
      TZ: Asia/Seoul
    ports:
      - "3308:3306"
    volumes:
      - mariadb_data:/var/lib/mysql
      - ./db/init/init.sql:/docker-entrypoint-initdb.d/init.sql

  backend:
    image: openjdk:21-jdk
    container_name: springboot_container
    restart: always
    depends_on:
      - db
    ports:
      - "8081:8081"
    environment:
      TZ: Asia/Seoul
    volumes:
      - ./backend/build/libs/ttalkkag-0.0.1-SNAPSHOT.jar:/app.jar  # JAR 파일을 마운트
    command: ["java", "-Dspring.profiles.active=dev", "-jar", "/app.jar"]

  nginx:
    image: nginx:latest
    container_name: vue_container
    restart: always
    ports:
      - "8080:8080"
    volumes:
      - ./frontend/dist:/usr/share/nginx/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - backend

  jenkins:
    container_name: jenkins
    build:
      dockerfile: Dockerfile
    environment:
      - TZ=Asia/Seoul
    user: root
    privileged: true
    volumes:
      - ./jenkins/config:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - 8085:8080
      - 50000:50000

volumes:
  mariadb_data:
