server:
  port: 8081
spring:
  application:
    name: ttalkkag
  datasource:
    url: jdbc:mariadb://192.168.50.63:3308/ttalkkag
    driver-class-name: org.mariadb.jdbc.Driver
    username: root
    password: 1234
  jpa:
    hibernate:
      ddl-auto: none
  mail:
    host: smtp.gmail.com
    port: 587
    username: dayomi19@gmail.com
    password: cmhn cmfy mfmv wapr
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.apitester.ttalkkag.dto

jwt:
  secret: LdqLV8d0ebKHnGek2HIOvmVtCaQHt914k7mTEZQYo33m2SUzvSVgWrBwzN2gnQ1rR0Joq90Lp9D7mFx0FLMQ1mwuV32ufB
  expiration: 7200000 # 7200000 2 hour
  refresh-expiration: 1209600033 # 1209600033 2 week

cors:
  allowed:
    origin: http://192.168.50.63:8080
